#endpoints.shutdown.enabled: true
multipart.maxFileSize: 100MB
multipart.maxRequestSize: 100MB

server.port: 8080
server.contextPath: /wp/ip2loc/
management.port: 9001
management.context-path: ${server.contextPath}
multipart:
  location: /net/isilonP/public/rw/homes/es_adm/ip2location/tmp-dir

---
spring:
  profiles: default
  paths:
    db: /ebi/extserv/local_work/ip2location/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE.BIN
    license: /ebi/extserv/local_work/ip2location/license.key

---
spring:
  profiles: dev_szymon
  paths:
    db: /Users/chojnasm/Data/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE.BIN
    license: /Users/chojnasm/Data/license.key

