#endpoints.shutdown.enabled: true
#multipart.maxFileSize: 100MB
#multipart.maxRequestSize: 100MB

server.port: 8080
server.contextPath: /wp/ip2loc/
management.port: 9001
management.context-path: ${server.contextPath}

---
spring:
  profiles: default
  paths:
    db: IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE.BIN
    license: license.key

---
spring:
  profiles: dev
  paths:
    db: your-path
    license: your-license

